package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="MODULE"
    ,catalog="db_21511543"
)
public class Module  implements java.io.Serializable {


     private int idModule;
     private String nameModule;
     private String descModule;
     private Set<User> users = new HashSet<User>(0);

    public Module() {
    }

	
    public Module(int idModule) {
        this.idModule = idModule;
    }
    public Module(int idModule, String nameModule, String descModule, Set<User> users) {
       this.idModule = idModule;
       this.nameModule = nameModule;
       this.descModule = descModule;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="ID_MODULE", unique=true, nullable=false)
    public int getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(int idModule) {
        this.idModule = idModule;
    }

    
    @Column(name="NAME_MODULE", length=32)
    public String getNameModule() {
        return this.nameModule;
    }
    
    public void setNameModule(String nameModule) {
        this.nameModule = nameModule;
    }

    
    @Column(name="DESC_MODULE")
    public String getDescModule() {
        return this.descModule;
    }
    
    public void setDescModule(String descModule) {
        this.descModule = descModule;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="modules")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


