package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="PERMISSION"
    ,catalog="db_21511543"
)
public class Permission  implements java.io.Serializable {


     private int idPerm;
     private String namePerm;
     private String descPerm;
     private Set<Role> roles = new HashSet<Role>(0);

    public Permission() {
    }

	
    public Permission(int idPerm) {
        this.idPerm = idPerm;
    }
    public Permission(int idPerm, String namePerm, String descPerm, Set<Role> roles) {
       this.idPerm = idPerm;
       this.namePerm = namePerm;
       this.descPerm = descPerm;
       this.roles = roles;
    }
   
     @Id 

    
    @Column(name="ID_PERM", unique=true, nullable=false)
    public int getIdPerm() {
        return this.idPerm;
    }
    
    public void setIdPerm(int idPerm) {
        this.idPerm = idPerm;
    }

    
    @Column(name="NAME_PERM", length=32)
    public String getNamePerm() {
        return this.namePerm;
    }
    
    public void setNamePerm(String namePerm) {
        this.namePerm = namePerm;
    }

    
    @Column(name="DESC_PERM")
    public String getDescPerm() {
        return this.descPerm;
    }
    
    public void setDescPerm(String descPerm) {
        this.descPerm = descPerm;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="CONTAIN", catalog="db_21511543", joinColumns = { 
        @JoinColumn(name="ID_PERM", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ID_RULE", nullable=false, updatable=false) })
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


