package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Po generated by hbm2java
 */
@Entity
@Table(name="PO"
    ,catalog="db_21511543"
)
public class Po  implements java.io.Serializable {


     private String po;
     private Customer customer;
     private Supplier supplier;
     private Date creationDate;
     private Date erpCreationDate;
     private String currency;
     private String documentType;
     private String codeTermPay;
     private String descTermPay;
     private Set<PoLine> poLines = new HashSet<PoLine>(0);

    public Po() {
    }

	
    public Po(String po, Customer customer, Supplier supplier) {
        this.po = po;
        this.customer = customer;
        this.supplier = supplier;
    }
    public Po(String po, Customer customer, Supplier supplier, Date creationDate, Date erpCreationDate, String currency, String documentType, String codeTermPay, String descTermPay, Set<PoLine> poLines) {
       this.po = po;
       this.customer = customer;
       this.supplier = supplier;
       this.creationDate = creationDate;
       this.erpCreationDate = erpCreationDate;
       this.currency = currency;
       this.documentType = documentType;
       this.codeTermPay = codeTermPay;
       this.descTermPay = descTermPay;
       this.poLines = poLines;
    }
   
     @Id 

    
    @Column(name="PO", unique=true, nullable=false, length=32)
    public String getPo() {
        return this.po;
    }
    
    public void setPo(String po) {
        this.po = po;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CUSTOMER", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SUPPLIER", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ERP_CREATION_DATE", length=19)
    public Date getErpCreationDate() {
        return this.erpCreationDate;
    }
    
    public void setErpCreationDate(Date erpCreationDate) {
        this.erpCreationDate = erpCreationDate;
    }

    
    @Column(name="CURRENCY", length=32)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="DOCUMENT_TYPE", length=32)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    
    @Column(name="CODE_TERM_PAY", length=32)
    public String getCodeTermPay() {
        return this.codeTermPay;
    }
    
    public void setCodeTermPay(String codeTermPay) {
        this.codeTermPay = codeTermPay;
    }

    
    @Column(name="DESC_TERM_PAY", length=32)
    public String getDescTermPay() {
        return this.descTermPay;
    }
    
    public void setDescTermPay(String descTermPay) {
        this.descTermPay = descTermPay;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="po")
    public Set<PoLine> getPoLines() {
        return this.poLines;
    }
    
    public void setPoLines(Set<PoLine> poLines) {
        this.poLines = poLines;
    }




}


