package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Po generated by hbm2java
 */
@Entity
@Table(name="PO"
    ,catalog="db_21511543"
)
public class Po  implements java.io.Serializable {


     private String numPo;
     private Customer customer;
     private Supplier supplier;
     private Date creationDate;
     private Date erpCreationDate;
     private String currency;
     private String documentType;
     private String codeTermPay;
     private String descTermPay;
     private Set<PoLine> poLines = new HashSet<PoLine>(0);

    public Po() {
    }

	
    public Po(String numPo, Customer customer, Supplier supplier) {
        this.numPo = numPo;
        this.customer = customer;
        this.supplier = supplier;
    }
    public Po(String numPo, Customer customer, Supplier supplier, Date creationDate, Date erpCreationDate, String currency, String documentType, String codeTermPay, String descTermPay, Set<PoLine> poLines) {
       this.numPo = numPo;
       this.customer = customer;
       this.supplier = supplier;
       this.creationDate = creationDate;
       this.erpCreationDate = erpCreationDate;
       this.currency = currency;
       this.documentType = documentType;
       this.codeTermPay = codeTermPay;
       this.descTermPay = descTermPay;
       this.poLines = poLines;
    }
   
     @Id 

     
    
    @Column(name="NUM_PO", unique=true, nullable=false, length=32)
    public String getNumPo() {
        return this.numPo;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.numPo);
        hash = 71 * hash + Objects.hashCode(this.customer);
        hash = 71 * hash + Objects.hashCode(this.supplier);
        hash = 71 * hash + Objects.hashCode(this.creationDate);
        hash = 71 * hash + Objects.hashCode(this.erpCreationDate);
        hash = 71 * hash + Objects.hashCode(this.currency);
        hash = 71 * hash + Objects.hashCode(this.documentType);
        hash = 71 * hash + Objects.hashCode(this.codeTermPay);
        hash = 71 * hash + Objects.hashCode(this.descTermPay);
        hash = 71 * hash + Objects.hashCode(this.poLines);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Po other = (Po) obj;
        if (!Objects.equals(this.numPo, other.numPo)) {
            return false;
        }
        if (!Objects.equals(this.currency, other.currency)) {
            return false;
        }
        if (!Objects.equals(this.documentType, other.documentType)) {
            return false;
        }
        if (!Objects.equals(this.codeTermPay, other.codeTermPay)) {
            return false;
        }
        if (!Objects.equals(this.descTermPay, other.descTermPay)) {
            return false;
        }
        if (!Objects.equals(this.customer, other.customer)) {
            return false;
        }
        if (!Objects.equals(this.supplier, other.supplier)) {
            return false;
        }
        if (!Objects.equals(this.creationDate, other.creationDate)) {
            return false;
        }
        if (!Objects.equals(this.erpCreationDate, other.erpCreationDate)) {
            return false;
        }
        if (!Objects.equals(this.poLines, other.poLines)) {
            return false;
        }
        return true;
    }
    
    public void setNumPo(String numPo) {
        this.numPo = numPo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NAME_CUSTOMER", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SUPPLIER", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ERP_CREATION_DATE", length=19)
    public Date getErpCreationDate() {
        return this.erpCreationDate;
    }
    
    public void setErpCreationDate(Date erpCreationDate) {
        this.erpCreationDate = erpCreationDate;
    }

    
    @Column(name="CURRENCY", length=32)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="DOCUMENT_TYPE", length=32)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    
    @Column(name="CODE_TERM_PAY", length=32)
    public String getCodeTermPay() {
        return this.codeTermPay;
    }
    
    public void setCodeTermPay(String codeTermPay) {
        this.codeTermPay = codeTermPay;
    }

    
    @Column(name="DESC_TERM_PAY", length=32)
    public String getDescTermPay() {
        return this.descTermPay;
    }
    
    public void setDescTermPay(String descTermPay) {
        this.descTermPay = descTermPay;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="po")
    public Set<PoLine> getPoLines() {
        return this.poLines;
    }
    
    public void setPoLines(Set<PoLine> poLines) {
        this.poLines = poLines;
    }




}


