package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoLineId generated by hbm2java
 */
@Embeddable
public class PoLineId  implements java.io.Serializable {


     private String numPo;
     private int idProduct;
     private int idUser;
     private Date dateModif;
     private String poLine;

    public PoLineId() {
    }

    public PoLineId(String numPo, int idProduct, int idUser, Date dateModif, String poLine) {
       this.numPo = numPo;
       this.idProduct = idProduct;
       this.idUser = idUser;
       this.dateModif = dateModif;
       this.poLine = poLine;
    }
   


    @Column(name="NUM_PO", nullable=false, length=32)
    public String getNumPo() {
        return this.numPo;
    }
    
    public void setNumPo(String numPo) {
        this.numPo = numPo;
    }


    @Column(name="ID_PRODUCT", nullable=false)
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }


    @Column(name="ID_USER", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="DATE_MODIF", nullable=false, length=19)
    public Date getDateModif() {
        return this.dateModif;
    }
    
    public void setDateModif(Date dateModif) {
        this.dateModif = dateModif;
    }


    @Column(name="PO_LINE", nullable=false, length=32)
    public String getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(String poLine) {
        this.poLine = poLine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoLineId) ) return false;
		 PoLineId castOther = ( PoLineId ) other; 
         
		 return ( (this.getNumPo()==castOther.getNumPo()) || ( this.getNumPo()!=null && castOther.getNumPo()!=null && this.getNumPo().equals(castOther.getNumPo()) ) )
 && (this.getIdProduct()==castOther.getIdProduct())
 && (this.getIdUser()==castOther.getIdUser())
 && ( (this.getDateModif()==castOther.getDateModif()) || ( this.getDateModif()!=null && castOther.getDateModif()!=null && this.getDateModif().equals(castOther.getDateModif()) ) )
 && ( (this.getPoLine()==castOther.getPoLine()) || ( this.getPoLine()!=null && castOther.getPoLine()!=null && this.getPoLine().equals(castOther.getPoLine()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumPo() == null ? 0 : this.getNumPo().hashCode() );
         result = 37 * result + this.getIdProduct();
         result = 37 * result + this.getIdUser();
         result = 37 * result + ( getDateModif() == null ? 0 : this.getDateModif().hashCode() );
         result = 37 * result + ( getPoLine() == null ? 0 : this.getPoLine().hashCode() );
         return result;
   }   


}


