package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoLineId generated by hbm2java
 */
@Embeddable
public class PoLineId  implements java.io.Serializable {


     private String po;
     private int id;
     private int idUser;
     private Date dateModif;
     private int poLine;

    public PoLineId() {
    }

    public PoLineId(String po, int id, int idUser, Date dateModif, int poLine) {
       this.po = po;
       this.id = id;
       this.idUser = idUser;
       this.dateModif = dateModif;
       this.poLine = poLine;
    }
   


    @Column(name="PO", nullable=false, length=32)
    public String getPo() {
        return this.po;
    }
    
    public void setPo(String po) {
        this.po = po;
    }


    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="ID_USER", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="DATE_MODIF", nullable=false, length=19)
    public Date getDateModif() {
        return this.dateModif;
    }
    
    public void setDateModif(Date dateModif) {
        this.dateModif = dateModif;
    }


    @Column(name="PO_LINE", nullable=false)
    public int getPoLine() {
        return this.poLine;
    }
    
    public void setPoLine(int poLine) {
        this.poLine = poLine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoLineId) ) return false;
		 PoLineId castOther = ( PoLineId ) other; 
         
		 return ( (this.getPo()==castOther.getPo()) || ( this.getPo()!=null && castOther.getPo()!=null && this.getPo().equals(castOther.getPo()) ) )
 && (this.getId()==castOther.getId())
 && (this.getIdUser()==castOther.getIdUser())
 && ( (this.getDateModif()==castOther.getDateModif()) || ( this.getDateModif()!=null && castOther.getDateModif()!=null && this.getDateModif().equals(castOther.getDateModif()) ) )
 && (this.getPoLine()==castOther.getPoLine());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPo() == null ? 0 : this.getPo().hashCode() );
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdUser();
         result = 37 * result + ( getDateModif() == null ? 0 : this.getDateModif().hashCode() );
         result = 37 * result + this.getPoLine();
         return result;
   }   


}


