package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoLine generated by hbm2java
 */
@Entity
@Table(name="PO_LINE"
    ,catalog="db_21511543"
)
public class PoLine  implements java.io.Serializable {


     private PoLineId id;
     private Po po;
     private Product product;
     private User user;
     private Integer quantityRequest;
     private Integer quantityPromised;
     private Integer quantityReceived;
     private BigDecimal unitPrice;
     private BigDecimal totalPrice;
     private BigDecimal unitPriceOriginal;
     private String lineComment;
     private String status;
     private Date requestDate;
     private Date promiseDate;

    public PoLine() {
    }

	
    public PoLine(PoLineId id, Po po, Product product, User user) {
        this.id = id;
        this.po = po;
        this.product = product;
        this.user = user;
    }
    public PoLine(PoLineId id, Po po, Product product, User user, Integer quantityRequest, Integer quantityPromised, Integer quantityReceived, BigDecimal unitPrice, BigDecimal totalPrice, BigDecimal unitPriceOriginal, String lineComment, String status, Date requestDate, Date promiseDate) {
       this.id = id;
       this.po = po;
       this.product = product;
       this.user = user;
       this.quantityRequest = quantityRequest;
       this.quantityPromised = quantityPromised;
       this.quantityReceived = quantityReceived;
       this.unitPrice = unitPrice;
       this.totalPrice = totalPrice;
       this.unitPriceOriginal = unitPriceOriginal;
       this.lineComment = lineComment;
       this.status = status;
       this.requestDate = requestDate;
       this.promiseDate = promiseDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numPo", column=@Column(name="NUM_PO", nullable=false, length=32) ), 
        @AttributeOverride(name="idProduct", column=@Column(name="ID_PRODUCT", nullable=false) ), 
        @AttributeOverride(name="idUser", column=@Column(name="ID_USER", nullable=false) ), 
        @AttributeOverride(name="dateModif", column=@Column(name="DATE_MODIF", nullable=false, length=19) ), 
        @AttributeOverride(name="poLine", column=@Column(name="PO_LINE", nullable=false, length=32) ) } )
    public PoLineId getId() {
        return this.id;
    }
    
    public void setId(PoLineId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUM_PO", nullable=false, insertable=false, updatable=false)
    public Po getPo() {
        return this.po;
    }
    
    public void setPo(Po po) {
        this.po = po;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCT", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="QUANTITY_REQUEST")
    public Integer getQuantityRequest() {
        return this.quantityRequest;
    }
    
    public void setQuantityRequest(Integer quantityRequest) {
        this.quantityRequest = quantityRequest;
    }

    
    @Column(name="QUANTITY_PROMISED")
    public Integer getQuantityPromised() {
        return this.quantityPromised;
    }
    
    public void setQuantityPromised(Integer quantityPromised) {
        this.quantityPromised = quantityPromised;
    }

    
    @Column(name="QUANTITY_RECEIVED")
    public Integer getQuantityReceived() {
        return this.quantityReceived;
    }
    
    public void setQuantityReceived(Integer quantityReceived) {
        this.quantityReceived = quantityReceived;
    }

    
    @Column(name="UNIT_PRICE", precision=10)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="TOTAL_PRICE", precision=10)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="UNIT_PRICE_ORIGINAL", precision=10)
    public BigDecimal getUnitPriceOriginal() {
        return this.unitPriceOriginal;
    }
    
    public void setUnitPriceOriginal(BigDecimal unitPriceOriginal) {
        this.unitPriceOriginal = unitPriceOriginal;
    }

    
    @Column(name="LINE_COMMENT", length=32)
    public String getLineComment() {
        return this.lineComment;
    }
    
    public void setLineComment(String lineComment) {
        this.lineComment = lineComment;
    }

    
    @Column(name="STATUS", length=32)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_DATE", length=19)
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PROMISE_DATE", length=19)
    public Date getPromiseDate() {
        return this.promiseDate;
    }
    
    public void setPromiseDate(Date promiseDate) {
        this.promiseDate = promiseDate;
    }

    @Override
    public String toString() {
        return "PoLine{" + "id=" + id + ", po=" + po + ", product=" + product + ", user=" + user + ", quantityRequest=" + quantityRequest + ", quantityPromised=" + quantityPromised + ", quantityReceived=" + quantityReceived + ", unitPrice=" + unitPrice + ", totalPrice=" + totalPrice + ", unitPriceOriginal=" + unitPriceOriginal + ", lineComment=" + lineComment + ", status=" + status + ", requestDate=" + requestDate + ", promiseDate=" + promiseDate + '}';
    }




}


