package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrevConsumId generated by hbm2java
 */
@Embeddable
public class PrevConsumId  implements java.io.Serializable {


     private Date datePrevConsume;
     private int idVmi;
     private int vmiRf;

    public PrevConsumId() {
    }

    public PrevConsumId(Date datePrevConsume, int idVmi, int vmiRf) {
       this.datePrevConsume = datePrevConsume;
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
    }
   


    @Column(name="DATE_PREV_CONSUME", nullable=false, length=19)
    public Date getDatePrevConsume() {
        return this.datePrevConsume;
    }
    
    public void setDatePrevConsume(Date datePrevConsume) {
        this.datePrevConsume = datePrevConsume;
    }


    @Column(name="ID_VMI", nullable=false)
    public int getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(int idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false)
    public int getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(int vmiRf) {
        this.vmiRf = vmiRf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrevConsumId) ) return false;
		 PrevConsumId castOther = ( PrevConsumId ) other; 
         
		 return ( (this.getDatePrevConsume()==castOther.getDatePrevConsume()) || ( this.getDatePrevConsume()!=null && castOther.getDatePrevConsume()!=null && this.getDatePrevConsume().equals(castOther.getDatePrevConsume()) ) )
 && (this.getIdVmi()==castOther.getIdVmi())
 && (this.getVmiRf()==castOther.getVmiRf());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDatePrevConsume() == null ? 0 : this.getDatePrevConsume().hashCode() );
         result = 37 * result + this.getIdVmi();
         result = 37 * result + this.getVmiRf();
         return result;
   }   


}


