package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrevConsumId generated by hbm2java
 */
@Embeddable
public class PrevConsumId  implements java.io.Serializable {


     private Date datePrevConsume;
     private String idVmi;
     private String vmiRf;

    public PrevConsumId() {
    }

    public PrevConsumId(Date datePrevConsume, String idVmi, String vmiRf) {
       this.datePrevConsume = datePrevConsume;
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
    }
   


    @Column(name="DATE_PREV_CONSUME", nullable=false, length=19)
    public Date getDatePrevConsume() {
        return this.datePrevConsume;
    }
    
    public void setDatePrevConsume(Date datePrevConsume) {
        this.datePrevConsume = datePrevConsume;
    }


    @Column(name="ID_VMI", nullable=false, length=128)
    public String getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(String idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false, length=128)
    public String getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(String vmiRf) {
        this.vmiRf = vmiRf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrevConsumId) ) return false;
		 PrevConsumId castOther = ( PrevConsumId ) other; 
         
		 return ( (this.getDatePrevConsume()==castOther.getDatePrevConsume()) || ( this.getDatePrevConsume()!=null && castOther.getDatePrevConsume()!=null && this.getDatePrevConsume().equals(castOther.getDatePrevConsume()) ) )
 && ( (this.getIdVmi()==castOther.getIdVmi()) || ( this.getIdVmi()!=null && castOther.getIdVmi()!=null && this.getIdVmi().equals(castOther.getIdVmi()) ) )
 && ( (this.getVmiRf()==castOther.getVmiRf()) || ( this.getVmiRf()!=null && castOther.getVmiRf()!=null && this.getVmiRf().equals(castOther.getVmiRf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDatePrevConsume() == null ? 0 : this.getDatePrevConsume().hashCode() );
         result = 37 * result + ( getIdVmi() == null ? 0 : this.getIdVmi().hashCode() );
         result = 37 * result + ( getVmiRf() == null ? 0 : this.getVmiRf().hashCode() );
         return result;
   }   


}


