package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrevDelivId generated by hbm2java
 */
@Embeddable
public class PrevDelivId  implements java.io.Serializable {


     private int idVmi;
     private int vmiRf;
     private Date datePrevDeliv;

    public PrevDelivId() {
    }

    public PrevDelivId(int idVmi, int vmiRf, Date datePrevDeliv) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
       this.datePrevDeliv = datePrevDeliv;
    }
   


    @Column(name="ID_VMI", nullable=false)
    public int getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(int idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false)
    public int getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(int vmiRf) {
        this.vmiRf = vmiRf;
    }


    @Column(name="DATE_PREV_DELIV", nullable=false, length=19)
    public Date getDatePrevDeliv() {
        return this.datePrevDeliv;
    }
    
    public void setDatePrevDeliv(Date datePrevDeliv) {
        this.datePrevDeliv = datePrevDeliv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrevDelivId) ) return false;
		 PrevDelivId castOther = ( PrevDelivId ) other; 
         
		 return (this.getIdVmi()==castOther.getIdVmi())
 && (this.getVmiRf()==castOther.getVmiRf())
 && ( (this.getDatePrevDeliv()==castOther.getDatePrevDeliv()) || ( this.getDatePrevDeliv()!=null && castOther.getDatePrevDeliv()!=null && this.getDatePrevDeliv().equals(castOther.getDatePrevDeliv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVmi();
         result = 37 * result + this.getVmiRf();
         result = 37 * result + ( getDatePrevDeliv() == null ? 0 : this.getDatePrevDeliv().hashCode() );
         return result;
   }   


}


