package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrevDelivId generated by hbm2java
 */
@Embeddable
public class PrevDelivId  implements java.io.Serializable {


     private String idVmi;
     private String vmiRf;
     private Date datePrevDeliv;

    public PrevDelivId() {
    }

    public PrevDelivId(String idVmi, String vmiRf, Date datePrevDeliv) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
       this.datePrevDeliv = datePrevDeliv;
    }
   


    @Column(name="ID_VMI", nullable=false, length=128)
    public String getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(String idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false, length=128)
    public String getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(String vmiRf) {
        this.vmiRf = vmiRf;
    }


    @Column(name="DATE_PREV_DELIV", nullable=false, length=19)
    public Date getDatePrevDeliv() {
        return this.datePrevDeliv;
    }
    
    public void setDatePrevDeliv(Date datePrevDeliv) {
        this.datePrevDeliv = datePrevDeliv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrevDelivId) ) return false;
		 PrevDelivId castOther = ( PrevDelivId ) other; 
         
		 return ( (this.getIdVmi()==castOther.getIdVmi()) || ( this.getIdVmi()!=null && castOther.getIdVmi()!=null && this.getIdVmi().equals(castOther.getIdVmi()) ) )
 && ( (this.getVmiRf()==castOther.getVmiRf()) || ( this.getVmiRf()!=null && castOther.getVmiRf()!=null && this.getVmiRf().equals(castOther.getVmiRf()) ) )
 && ( (this.getDatePrevDeliv()==castOther.getDatePrevDeliv()) || ( this.getDatePrevDeliv()!=null && castOther.getDatePrevDeliv()!=null && this.getDatePrevDeliv().equals(castOther.getDatePrevDeliv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVmi() == null ? 0 : this.getIdVmi().hashCode() );
         result = 37 * result + ( getVmiRf() == null ? 0 : this.getVmiRf().hashCode() );
         result = 37 * result + ( getDatePrevDeliv() == null ? 0 : this.getDatePrevDeliv().hashCode() );
         return result;
   }   


}


