package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="PRODUCT"
    ,catalog="db_21511543"
)
public class Product  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private Supplier supplier;
     private String unit;
     private String refSupplier;
     private String descSupplier;
     private String refCustomer;
     private String descCustomer;
     private Set<PoLine> poLines = new HashSet<PoLine>(0);
     private Set<Vmi> vmis = new HashSet<Vmi>(0);

    public Product() {
    }

	
    public Product(int id, Customer customer, Supplier supplier) {
        this.id = id;
        this.customer = customer;
        this.supplier = supplier;
    }
    public Product(int id, Customer customer, Supplier supplier, String unit, String refSupplier, String descSupplier, String refCustomer, String descCustomer, Set<PoLine> poLines, Set<Vmi> vmis) {
       this.id = id;
       this.customer = customer;
       this.supplier = supplier;
       this.unit = unit;
       this.refSupplier = refSupplier;
       this.descSupplier = descSupplier;
       this.refCustomer = refCustomer;
       this.descCustomer = descCustomer;
       this.poLines = poLines;
       this.vmis = vmis;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CUSTOMER", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SUPPLIER", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="UNIT", length=32)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    @Column(name="REF_SUPPLIER", length=32)
    public String getRefSupplier() {
        return this.refSupplier;
    }
    
    public void setRefSupplier(String refSupplier) {
        this.refSupplier = refSupplier;
    }

    
    @Column(name="DESC_SUPPLIER")
    public String getDescSupplier() {
        return this.descSupplier;
    }
    
    public void setDescSupplier(String descSupplier) {
        this.descSupplier = descSupplier;
    }

    
    @Column(name="REF_CUSTOMER", length=32)
    public String getRefCustomer() {
        return this.refCustomer;
    }
    
    public void setRefCustomer(String refCustomer) {
        this.refCustomer = refCustomer;
    }

    
    @Column(name="DESC_CUSTOMER")
    public String getDescCustomer() {
        return this.descCustomer;
    }
    
    public void setDescCustomer(String descCustomer) {
        this.descCustomer = descCustomer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<PoLine> getPoLines() {
        return this.poLines;
    }
    
    public void setPoLines(Set<PoLine> poLines) {
        this.poLines = poLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Vmi> getVmis() {
        return this.vmis;
    }
    
    public void setVmis(Set<Vmi> vmis) {
        this.vmis = vmis;
    }




}


