package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StatusStockId generated by hbm2java
 */
@Embeddable
public class StatusStockId  implements java.io.Serializable {


     private String idVmi;
     private String vmiRf;
     private Date dateStatusStock;

    public StatusStockId() {
    }

    public StatusStockId(String idVmi, String vmiRf, Date dateStatusStock) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
       this.dateStatusStock = dateStatusStock;
    }
   


    @Column(name="ID_VMI", nullable=false, length=128)
    public String getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(String idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false, length=128)
    public String getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(String vmiRf) {
        this.vmiRf = vmiRf;
    }


    @Column(name="DATE_STATUS_STOCK", nullable=false, length=19)
    public Date getDateStatusStock() {
        return this.dateStatusStock;
    }
    
    public void setDateStatusStock(Date dateStatusStock) {
        this.dateStatusStock = dateStatusStock;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StatusStockId) ) return false;
		 StatusStockId castOther = ( StatusStockId ) other; 
         
		 return ( (this.getIdVmi()==castOther.getIdVmi()) || ( this.getIdVmi()!=null && castOther.getIdVmi()!=null && this.getIdVmi().equals(castOther.getIdVmi()) ) )
 && ( (this.getVmiRf()==castOther.getVmiRf()) || ( this.getVmiRf()!=null && castOther.getVmiRf()!=null && this.getVmiRf().equals(castOther.getVmiRf()) ) )
 && ( (this.getDateStatusStock()==castOther.getDateStatusStock()) || ( this.getDateStatusStock()!=null && castOther.getDateStatusStock()!=null && this.getDateStatusStock().equals(castOther.getDateStatusStock()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVmi() == null ? 0 : this.getIdVmi().hashCode() );
         result = 37 * result + ( getVmiRf() == null ? 0 : this.getVmiRf().hashCode() );
         result = 37 * result + ( getDateStatusStock() == null ? 0 : this.getDateStatusStock().hashCode() );
         return result;
   }   


}


