package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StatusStockId generated by hbm2java
 */
@Embeddable
public class StatusStockId  implements java.io.Serializable {


     private int idVmi;
     private int vmiRf;
     private Date dateStatusStock;

    public StatusStockId() {
    }

    public StatusStockId(int idVmi, int vmiRf, Date dateStatusStock) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
       this.dateStatusStock = dateStatusStock;
    }
   


    @Column(name="ID_VMI", nullable=false)
    public int getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(int idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false)
    public int getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(int vmiRf) {
        this.vmiRf = vmiRf;
    }


    @Column(name="DATE_STATUS_STOCK", nullable=false, length=19)
    public Date getDateStatusStock() {
        return this.dateStatusStock;
    }
    
    public void setDateStatusStock(Date dateStatusStock) {
        this.dateStatusStock = dateStatusStock;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StatusStockId) ) return false;
		 StatusStockId castOther = ( StatusStockId ) other; 
         
		 return (this.getIdVmi()==castOther.getIdVmi())
 && (this.getVmiRf()==castOther.getVmiRf())
 && ( (this.getDateStatusStock()==castOther.getDateStatusStock()) || ( this.getDateStatusStock()!=null && castOther.getDateStatusStock()!=null && this.getDateStatusStock().equals(castOther.getDateStatusStock()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVmi();
         result = 37 * result + this.getVmiRf();
         result = 37 * result + ( getDateStatusStock() == null ? 0 : this.getDateStatusStock().hashCode() );
         return result;
   }   


}


