package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="SUPPLIER"
    ,catalog="db_21511543"
)
public class Supplier  implements java.io.Serializable {


     private int idSupplier;
     private String nameSupplier;
     private String streetSupplier;
     private String zipSupplier;
     private String citySupplier;
     private String countrySupplier;
     private Set<Po> pos = new HashSet<Po>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Vmi> vmis = new HashSet<Vmi>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Supplier() {
    }

	
    public Supplier(int idSupplier) {
        this.idSupplier = idSupplier;
    }
    public Supplier(int idSupplier, String nameSupplier, String streetSupplier, String zipSupplier, String citySupplier, String countrySupplier, Set<Po> pos, Set<User> users, Set<Vmi> vmis, Set<Product> products) {
       this.idSupplier = idSupplier;
       this.nameSupplier = nameSupplier;
       this.streetSupplier = streetSupplier;
       this.zipSupplier = zipSupplier;
       this.citySupplier = citySupplier;
       this.countrySupplier = countrySupplier;
       this.pos = pos;
       this.users = users;
       this.vmis = vmis;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="ID_SUPPLIER", unique=true, nullable=false)
    public int getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(int idSupplier) {
        this.idSupplier = idSupplier;
    }

    
    @Column(name="NAME_SUPPLIER", length=32)
    public String getNameSupplier() {
        return this.nameSupplier;
    }
    
    public void setNameSupplier(String nameSupplier) {
        this.nameSupplier = nameSupplier;
    }

    
    @Column(name="STREET_SUPPLIER", length=32)
    public String getStreetSupplier() {
        return this.streetSupplier;
    }
    
    public void setStreetSupplier(String streetSupplier) {
        this.streetSupplier = streetSupplier;
    }

    
    @Column(name="ZIP_SUPPLIER", length=5)
    public String getZipSupplier() {
        return this.zipSupplier;
    }
    
    public void setZipSupplier(String zipSupplier) {
        this.zipSupplier = zipSupplier;
    }

    
    @Column(name="CITY_SUPPLIER", length=32)
    public String getCitySupplier() {
        return this.citySupplier;
    }
    
    public void setCitySupplier(String citySupplier) {
        this.citySupplier = citySupplier;
    }

    
    @Column(name="COUNTRY_SUPPLIER", length=32)
    public String getCountrySupplier() {
        return this.countrySupplier;
    }
    
    public void setCountrySupplier(String countrySupplier) {
        this.countrySupplier = countrySupplier;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Po> getPos() {
        return this.pos;
    }
    
    public void setPos(Set<Po> pos) {
        this.pos = pos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Vmi> getVmis() {
        return this.vmis;
    }
    
    public void setVmis(Set<Vmi> vmis) {
        this.vmis = vmis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


