package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vmi generated by hbm2java
 */
@Entity
@Table(name="VMI"
    ,catalog="db_21511543"
)
public class Vmi  implements java.io.Serializable {


     private VmiId id;
     private Customer customer;
     private Product product;
     private ShippingAdress shippingAdress;
     private Supplier supplier;
     private String refItem;
     private String currency;
     private Date dateSend;
     private String codeTermPay;
     private String descTermPay;
     private BigDecimal price;
     private Date dateValidityPrice;
     private Set<StatusStock> statusStocks = new HashSet<StatusStock>(0);
     private Set<PrevDeliv> prevDelivs = new HashSet<PrevDeliv>(0);
     private Set<PrevConsum> prevConsums = new HashSet<PrevConsum>(0);

    public Vmi() {
    }

	
    public Vmi(VmiId id, Customer customer, Product product, ShippingAdress shippingAdress, Supplier supplier) {
        this.id = id;
        this.customer = customer;
        this.product = product;
        this.shippingAdress = shippingAdress;
        this.supplier = supplier;
    }
    public Vmi(VmiId id, Customer customer, Product product, ShippingAdress shippingAdress, Supplier supplier, String refItem, String currency, Date dateSend, String codeTermPay, String descTermPay, BigDecimal price, Date dateValidityPrice, Set<StatusStock> statusStocks, Set<PrevDeliv> prevDelivs, Set<PrevConsum> prevConsums) {
       this.id = id;
       this.customer = customer;
       this.product = product;
       this.shippingAdress = shippingAdress;
       this.supplier = supplier;
       this.refItem = refItem;
       this.currency = currency;
       this.dateSend = dateSend;
       this.codeTermPay = codeTermPay;
       this.descTermPay = descTermPay;
       this.price = price;
       this.dateValidityPrice = dateValidityPrice;
       this.statusStocks = statusStocks;
       this.prevDelivs = prevDelivs;
       this.prevConsums = prevConsums;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVmi", column=@Column(name="ID_VMI", nullable=false) ), 
        @AttributeOverride(name="vmiRf", column=@Column(name="VMI_RF", nullable=false) ) } )
    public VmiId getId() {
        return this.id;
    }
    
    public void setId(VmiId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CUSTOMER", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ADRESS", nullable=false)
    public ShippingAdress getShippingAdress() {
        return this.shippingAdress;
    }
    
    public void setShippingAdress(ShippingAdress shippingAdress) {
        this.shippingAdress = shippingAdress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SUPPLIER", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="REF_ITEM", length=32)
    public String getRefItem() {
        return this.refItem;
    }
    
    public void setRefItem(String refItem) {
        this.refItem = refItem;
    }

    
    @Column(name="CURRENCY", length=32)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_SEND", length=19)
    public Date getDateSend() {
        return this.dateSend;
    }
    
    public void setDateSend(Date dateSend) {
        this.dateSend = dateSend;
    }

    
    @Column(name="CODE_TERM_PAY", length=32)
    public String getCodeTermPay() {
        return this.codeTermPay;
    }
    
    public void setCodeTermPay(String codeTermPay) {
        this.codeTermPay = codeTermPay;
    }

    
    @Column(name="DESC_TERM_PAY", length=32)
    public String getDescTermPay() {
        return this.descTermPay;
    }
    
    public void setDescTermPay(String descTermPay) {
        this.descTermPay = descTermPay;
    }

    
    @Column(name="PRICE", precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_VALIDITY_PRICE", length=19)
    public Date getDateValidityPrice() {
        return this.dateValidityPrice;
    }
    
    public void setDateValidityPrice(Date dateValidityPrice) {
        this.dateValidityPrice = dateValidityPrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vmi")
    public Set<StatusStock> getStatusStocks() {
        return this.statusStocks;
    }
    
    public void setStatusStocks(Set<StatusStock> statusStocks) {
        this.statusStocks = statusStocks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vmi")
    public Set<PrevDeliv> getPrevDelivs() {
        return this.prevDelivs;
    }
    
    public void setPrevDelivs(Set<PrevDeliv> prevDelivs) {
        this.prevDelivs = prevDelivs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vmi")
    public Set<PrevConsum> getPrevConsums() {
        return this.prevConsums;
    }
    
    public void setPrevConsums(Set<PrevConsum> prevConsums) {
        this.prevConsums = prevConsums;
    }




}


