package Business;
// Generated 28 mars 2017 12:22:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VmiId generated by hbm2java
 */
@Embeddable
public class VmiId  implements java.io.Serializable {


     private String idVmi;
     private String vmiRf;

    public VmiId() {
    }

    public VmiId(String idVmi, String vmiRf) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
    }
   


    @Column(name="ID_VMI", nullable=false, length=128)
    public String getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(String idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false, length=128)
    public String getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(String vmiRf) {
        this.vmiRf = vmiRf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VmiId) ) return false;
		 VmiId castOther = ( VmiId ) other; 
         
		 return ( (this.getIdVmi()==castOther.getIdVmi()) || ( this.getIdVmi()!=null && castOther.getIdVmi()!=null && this.getIdVmi().equals(castOther.getIdVmi()) ) )
 && ( (this.getVmiRf()==castOther.getVmiRf()) || ( this.getVmiRf()!=null && castOther.getVmiRf()!=null && this.getVmiRf().equals(castOther.getVmiRf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVmi() == null ? 0 : this.getIdVmi().hashCode() );
         result = 37 * result + ( getVmiRf() == null ? 0 : this.getVmiRf().hashCode() );
         return result;
   }   


}


