package Business;
// Generated 27 mars 2017 14:41:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VmiId generated by hbm2java
 */
@Embeddable
public class VmiId  implements java.io.Serializable {


     private int idVmi;
     private int vmiRf;

    public VmiId() {
    }

    public VmiId(int idVmi, int vmiRf) {
       this.idVmi = idVmi;
       this.vmiRf = vmiRf;
    }
   


    @Column(name="ID_VMI", nullable=false)
    public int getIdVmi() {
        return this.idVmi;
    }
    
    public void setIdVmi(int idVmi) {
        this.idVmi = idVmi;
    }


    @Column(name="VMI_RF", nullable=false)
    public int getVmiRf() {
        return this.vmiRf;
    }
    
    public void setVmiRf(int vmiRf) {
        this.vmiRf = vmiRf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VmiId) ) return false;
		 VmiId castOther = ( VmiId ) other; 
         
		 return (this.getIdVmi()==castOther.getIdVmi())
 && (this.getVmiRf()==castOther.getVmiRf());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVmi();
         result = 37 * result + this.getVmiRf();
         return result;
   }   


}


